// <auto-generated />
namespace RCOTruckApp.Models.DBContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ELDEvents : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ELDEvents));
        
        string IMigrationMetadata.Id
        {
            get { return "202210260250247_ELDEvents"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
