// <auto-generated />
namespace RCOTruckApp.Models.DBContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PreTripCheckList_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PreTripCheckList_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202210270608355_PreTripCheckList_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
